services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/bmo/VAULT/sonarr:/config
      - /media/bmo/MIMIC/jellyfin/media/Shows:/tv
      - /media/bmo/MIMIC/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped