services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/bmo/VAULT/radarr:/config
      - /media/bmo/MIMIC/jellyfin/media/Movies:/movies
      - /media/bmo/MIMIC/downloads:/downloads 
    ports:
      - 7878:7878
    restart: unless-stopped