services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
    volumes:
      - /media/bmo/VAULT/jellyfin/config:/config
      - /media/bmo/VAULT/jellyfin/cache:/cache
      - type: bind
        source: /media/bmo/MIMIC/jellyfin/media
        target: /media
    restart: unless-stopped
